#!/usr/bin/env bash

export CONTECO_LABEL="External controlplane image"
export CONTECO_DESCRIPTION="Creation of the external controlplane image for the ContEco ecosystem."

export CONTECO_TYPE="external"
export CONTECO_NAME="controlplane"
export CONTECO_TAG="1.0.0"

export CONTECO_BASE="external.bash:5.0.9"
export CONTECO_BUILD="external-extended"
