#!/usr/bin/env bash

export CONTECO_LABEL="external.controlplane - ContEco"
export CONTECO_DESCRIPTION="external.bash image with controlplane prerequisites installed."

export CONTECO_TYPE="external"
export CONTECO_NAME="controlplane"
export CONTECO_TAG="18.09.8"

export CONTECO_BASE="external.bash:5.0.18"
export CONTECO_BUILD="external-extended"
